### ISSUE TITLE
Error with MODIS Landcover Download Through R

### ISSUE THREAD

**Issue by mpalumbo56** [MatMatt/MODIS#66] opened 2019-03-28 16:01 UTC
Hi, 

I am trying to run the following lines of code in R, to access MODIS landcover information:

library(MODIS)
runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
        tileH = 10, tileV = 6,
        begin = "2016.01.01", end = "2016.12.31")

And I receive the output of:

> library(MODIS)
> runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
+         tileH = 10, tileV = 6,
+         begin = "2016.01.01", end = "2016.12.31")
########################
outProj          =  asIn 
pixelSize        =  asIn 
resamplingType   =  near 
Output directory =  C:/Users/mxpalumb/AppData/Local/Temp/RtmpM9ZcrC/MODIS_ARC/PROCESSED/MCD12Q1.006_20190328115516  (no 'job' name specified, generated (date/time based))
########################
Local structure is up-to-date. Using offline information!
Error in (function (x, ...)  : 
  Make sure either 'wget' or 'curl' is available in order to download data from LP DAAC or NSIDC.

Can anyone assist me with understanding how to make sure 'wget' or 'curl' is available? 

Thank you

**Comment by mstrimas** [comment] 2019-03-28 18:28
FYI I sent mpalumbo56 over from here: https://github.com/mstrimas/ebird-best-practices/issues/2

They're on Windows 7 and have both Cygwin and git bash installed.

**Comment by fdetsch** [comment] 2019-03-29 09:03
First of all, your code is syntactically correct. It runs perfectly smoothly on my machine.

As regards the error message above, are curl.exe and/or wget.exe made available through any of your environment variables? For example, I put both executables in `C:\Windows\System32`, which is in the system's PATH by default. Hence, my console output on the Windows command line looks something like this: 

```
>where curl
C:\Windows\System32\curl.exe

>where wget
C:\Windows\System32\wget.exe
```

This is exactly the information that **MODIS** needs in order to be able to download data from LP DAAC, which is the only server for MCD12Q1. If neither of the two files could be found, `runGdal()` (or rather `getHdf()`, which runs under the hood) exits with above error message.

@mstrimas Thanks for the referral.

**Comment by mstrimas** [comment] 2019-03-29 11:41
@mpalumbo56 It appears you either don't have curl or that it isn't in your PATH and therefore not accessible through R. I'm not sure why this is the case since you've installed both git bash and cygwin, which should have curl installed. Perhaps because you don't have admin privileges? Also, I'm on Windows 10, which apparently comes with curl by default and the same isn't true for Windows 7. I think [this StackOverflow question](https://stackoverflow.com/questions/9507353/how-do-i-install-and-use-curl-on-windows) could be helpful.

Can you check if there is a curl or wget executable in `C:\Program Files\Git\mingw64\bin\`. If one of them is there, the issue is that they're not in your path and the StackOverflow question linked in the previous paragraph explains how to fix that. If they aren't there, there must be something wrong with your git for windows installation. There are instructions for installing various other distributions of curl in that StackOverflow post.

**Comment by mpalumbo56** [comment] 2019-03-29 12:47
Success!!! 

On my computer (Windows 7), curl is present in C:\Program Files\Git\mingw64\bin\ and once I changed the path, per the StackOverflow thread, MODIS is able to download data from LP DAAC. 

Thank you very much for helping me sort this out.

**Comment by mstrimas** [comment] 2019-03-29 13:21
Great, glad to hear it's working! I'll add this to the book and close the issue on my repo. Thanks for sticking with it!

**Comment by fdetsch** [comment] 2019-04-01 07:15
Glad it finally works.

@mstrimas BTW, it was fun reading your tutorial on [downloading MODIS data](http://strimas.com/ebird-best-practices/habitat.html#habitat-dl). If there's anything we could do to make the package less "challenging and confusing to get working", as you put it, please let us know ;-)

**Closed by fdetsch** 2019-04-01 07:15 UTC

**Comment by mstrimas** [comment] 2019-04-01 11:54
Unfortunately, I think it's mostly dependency issues, so I don't know if there's much you can do on your end. We've sent the book out to a bunch of people for testing and in almost every case they got caught up with the MODIS chapter and I had to intervene. The primary issue is getting GDAL installed with HDF4 support, but there's also the curl issue mentioned in this thread. I've tried to give extremely explicit instructions for how to get these dependencies installed, but it doesn't seem to matter, users still get caught here. So, I put the warning in to let users know "hey, don't get discouraged, you might have trouble here, but you're not doing anything wrong, it's a common problem".

I think it would be valuable to have more detailed install instructions in the repo README, since it would probably make more sense for you to manage that directly.

**Comment by mstrimas** [comment] 2019-04-01 11:56
The package has been extremely helpful for putting together this bookdown document, without it we'd probably need to tell users how to manually download and mosaic the MODIS data, which would be a huge pain! Thanks for all your work putting it together!

**Comment by fdetsch** [comment] 2019-04-02 09:41
Thanks for the feedback. I agree that something like an installation vignette would make absolute sense. In addition, I'll probably include some additional resources (like your book), which might provide further details, in the repo's README.
