### ISSUE TITLE
Error with extractBits function on MOD15A2H QC layer

### ISSUE THREAD

**Issue by nhoyos** [MatMatt/MODIS#48] opened 2018-04-20 04:56 UTC
I used the extractBits function on MOD15A2H QC layer (MODLAND_QC parameter) and compared it to the output from the unpack_sds_bits LDOPE tool and realized they were quite different. I ran extractBits using: 
extractBits(QCraster, bitShift=0, bitMask=1, decodeOnly=TRUE)

After careful inspection, I found that when the QCraster has a decimal value of 0, the extractBits output has a value of 1 for MODLAND_QC. Shouldn´t it be zero (meaning high quality?). The unpack_sds_bits output does have a value of zero.

**Comment by fdetsch** [comment] 2018-07-11 15:15
@MatMatt `extractBits()` is your creation and I've never worked with it. Do you want to take a look into this?

**Comment by MatMatt** [comment] 2018-07-12 08:41
Ok! I'll look into that!

**Comment by MatMatt** [comment] 2018-07-12 14:35
@nhoyos 

I found a quite worrisome bug in the [bit extraction functions](https://github.com/MatMatt/MODIS/blob/develop/R/makeWeights.R). But I think it is not related to your issue: The encoding seems to be correct.

Please install the dev version to use the latest functions and use this code example below (change the selected tile if you wish), and report it in a way to allow us to easily reproduce the issue.

```
library(MODIS)

MOD15A2H <- runGdal(job="MOD15A2H", product="MOD15A2H", tileH=19, tileV=5, begin="2018177", end="2018177")
MOD15A2H

FparLai_QC <- raster(MOD15A2H$MOD15A2H.006$`2018-06-26`[3])
detectBitInfo("MOD15A2H")
d <- extractBits(FparLai_QC, bitShift = 0, bitMask = 1)
plot(d)
```

Note: extractBits does not have a decodeOnly argument.

**Comment by fdetsch** [comment] 2018-08-01 08:44
@MatMatt, any insights from the colleague you wanted to contact on this?

**Comment by MatMatt** [comment] 2018-08-01 16:10
I think we can close this issue. The changes in dev should also solve the error found by @nhoyos. 
MODLAND_QC is a binary mask 0/1. The 1 found by @nhoyos comes from those cases where all 5 'layers' in FparLai_QC have value 0. 
This was erroneously interpreted as NA by `extractBits` (instead of highest quality) and the maximum value 1 (in case of MODLAND_QC was given) was assigned consequently. This behaviour is corrected in dev.

**Closed** 2018-08-01 16:53 UTC
